name: random-trans
version: 0.1.0.0
#synopsis:
#description:
homepage: https://github.com/githubuser/random-trans#readme
license: BSD3
author: Author name here
maintainer: example@example.com
copyright: 2019 Author name here
category: Web
extra-source-files:
  - README.md

dependencies:
  - base >= 4.7 && < 5
  - containers
  - lens
  - MonadRandom
  - mtl
  - text
  - random
  - transformers
  - validation
  - optparse-applicative

executables:
  random-trans:
    source-dirs: src
    main: Main.hs
    ghc-options:
      - -Wall
